CREATE DATABASE DemoCrud
USE DemoCrud

CREATE TABLE StudentTB(
StudenID INT PRIMARY KEY,
Name NVARCHAR(50),
FatherName NVARCHAR(50),
RollNumber NVARCHAR(50),
Address NVARCHAR(200),
Mobile NVARCHAR(15)
)